freebsd_instance:
  image_family: freebsd-12-1

task:
  name: FreeBSD 12.0 amd64
  env:
    RUST_BACKTRACE: full
    HOME: /tmp # cargo needs it
  install_script: pkg install -y rust
  cargo_cache:
    folder: $HOME/.cargo/registry
    fingerprint_script: cat Cargo.toml
  build_script: cargo build
  test_script: cargo test
  before_cache_script: rm -rf $HOME/.cargo/registry/index
