language: rust
os: linux
dist: bionic

rust:
  - stable

script:
  - cargo test
  - bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
  - cargo tarpaulin --out Xml
  - bash <(curl -s https://codecov.io/bash)

cache:
  cargo: true
